In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import ast

In [108]:
df = pd.read_excel("final_db1.xlsx") # read excel file
df.head()

,EID,Title,Journal,DOI,anode/positive electrode,cathode/negative electrode,electrolyte,Specific Capacitance Value,Specific Capacitance Unit,Surface Area Value,...,Energy Density Value,Energy Density Unit,Power Density Value,Power Density Unit,Voltage Value,Voltage Unit,Current Density Value,Current Density Unit,Cycles Value,Cycles Unit
0,2-s2.0-85160588636,One-pot synthesis of N-doped petroleum coke-ba...,Journal of Environmental Sciences (China),10.1016/j.jes.2023.02.008,NaN,NaN,KOH,233.25,F/g,2512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,cycles
1,2-s2.0-85164280131,Interwoven of γ-MnO2 and V2O5 nanostructures w...,Fuel,10.1016/j.fuel.2023.129167,γ-MnO2,γ-MnO2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.50,V,NaN,NaN,1000,cycles
2,2-s2.0-85163550064,Facile synthesis of Co3O4@SeNPs grafted MWCNTs...,Chemical Physics Impact,10.1016/j.chphi.2023.100253,Co3O4,Co3O4,carbon,356,F/g,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2-s2.0-85159963802,Bimetallic Co–Fe sulfide and phosphide as effi...,Discover Nano,10.1186/s11671-023-03837-1,phosphorized CoFe,phosphorized CoFe,NaN,"252, 120",F/g,NaN,...,"4.3, 10.1",Wh/kg,"4.2, 3752","kW/kg, W/kg",NaN,NaN,10,mA/cm2,5000,cycles
4,2-s2.0-85159455937,Boosted electrochemical performance of magneti...,Scientific Reports,10.1038/s41598-023-35014-w,NaN,Mg0.5Ni0.5Fe2O4,KOH,647,F/g,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000,cycles

In [149]:
i = "Cycles Value"

In [150]:
def coma_split(item):
    try:
        if item is not None:
            values = item.split(', ')
            float_value = float(values[0])
            return float_value
        else:
            return None
    except AttributeError:
        return None

In [151]:
def count_num(item):
    try:
        if item is not None:
            values = item.split(', ')
            float_value = len(values)
            return float_value
        else:
            return 0
    except AttributeError:
        return 1

In [152]:
z = df[f"{i}_count"] = df[i].apply(count_num)

In [153]:
# print(df)

In [154]:
# df.to_excel('len_count.xlsx', index=False)

In [155]:
print(z.unique())

[1 2 3 4]

In [159]:
value_to_count = 1
count = (z == value_to_count).sum()
print(count)

27462